/*
 * whitelisting-api
 *
 * This API is used to whitelist members on our minecraft-server
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	ws "github.com/ledex/whitelisting-service/go"
)

func main() {
	log.Printf("Server started")

	router := ws.NewRouter()

	log.Fatal(http.ListenAndServe(":3000", router))
}
