openapi: 3.0.0
info:
  title: whitelisting-api
  version: '1.0'
  description: This API is used to whitelist members on our minecraft-server
servers:
  - url: 'http://173.212.208.2:3000'
    description: Prod
paths:
  /members:
    post:
      summary: Add a new member
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  id:
                    type: string
        '401':
          description: Unauthorized
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '500':
          description: Internal Server Error
      operationId: post-members
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
        description: ''
  '/members/{username}':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
        description: Username that should be removed from the whitelist.
    delete:
      summary: Delete an existing member
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: delete-members-id
      parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
security:
  - API Key - 1: []
