/*
 * whitelisting-api
 *
 * This API is used to whitelist members on our minecraft-server
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import "github.com/google/uuid"

type Body struct {
	Username string `json:"username,omitempty"`
}

type MojangUser struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type WhitelistEntry struct {
	Id uuid.UUID `json:"uuid"`
	Name string `json:"name"`
}
