/*
 * whitelisting-api
 *
 * This API is used to whitelist members on our minecraft-server
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{
	Route{
		"DeleteMembersId",
		strings.ToUpper("Delete"),
		"/members/{username}",
		DeleteMembersId,
	},

	Route{
		"PostMembers",
		strings.ToUpper("Post"),
		"/members",
		PostMembers,
	},

	Route{
		"GetMembers",
		strings.ToUpper("Get"),
		"/members",
		GetMembers,
	},
}
